### ISSUE TITLE
Error while npm start

### ISSUE THREAD

**Issue by staszewski** [codequest-eu/monsters-api#1]
Hi, after installing dependencies i get an error. Do i have to do something more besides installing dependencies to make it work? 
```
> monsters-api@1.0.0 start /home/kamil/Desktop/Projekty/Job Finder/server
> node index.js

/home/kamil/Desktop/Projekty/Job Finder/server/monsters.js:63
      name: monster.name, ...this.createMonsterDetails(monster)
                          ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kamil/Desktop/Projekty/Job Finder/server/index.js:3:18)
    at Module._compile (module.js:541:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! monsters-api@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the monsters-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kamil/.npm/_logs/2018-10-16T16_47_52_681Z-debug.log
```

**Comment by staszewski** [comment]
npm 6.4.1
nodejs 10.11.0

**Comment by piotrkabacinski** [comment]
Hi @KamilStaszewski, you should just install dependencies and be able to run the API. Unfortunately, I wasn't able to reproduce this issue using Node@10.11.0 and npm@6.4.1. The spread operator should be supported from 5.x version. Please try `harmony` flag (`node --harmony index.js`), if it won't help checkout to `spread-replace` branch and try it out. It changes spread operator to `Object.assign` to avoid spreading with noniterable object.
